---
- name: "Install Jenkins Agent"
  notify:
    - "Enable and start Jenkins Agent"
    - "Restart Jenkins Agent"
  block:
    - name: "Edit / Create the Jenkins group"
      ansible.builtin.group:
        name: "{{ install_jenkins_agent__group }}"
        state: present

    - name: "Edit / Create the Jenkins user, Docker based"
      when: install_jenkins_agent__docker_based | default(false)
      ansible.builtin.user:
        name: "{{ install_jenkins_agent__user }}"
        groups: "docker,{{ install_jenkins_agent__group }}"
        state: present
        append: true
        password: "{{ install_jenkins_agent__password }}"

    - name: "Edit / Create the Jenkins user, no Docker based"
      when: not (install_jenkins_agent__docker_based | default(false))
      ansible.builtin.user:
        name: "{{ install_jenkins_agent__user }}"
        groups: "{{ install_jenkins_agent__group }}"
        state: present
        append: true
        password: "{{ install_jenkins_agent__password }}"

    - name: "Check if folder home exist"
      register: folder_check
      ansible.builtin.stat:
        path: "{{ install_jenkins_agent__home }}"

    - name: "Create home path"
      when: not folder_check.stat.exists
      ansible.builtin.file:
        path: "{{ install_jenkins_agent__home }}"
        state: directory
        recurse: yes
        mode: "0700"
        group: "{{ install_jenkins_agent__group }}"
        owner: "{{ install_jenkins_agent__user }}"

    - name: "Check if log folder exist"
      register: folder_check
      ansible.builtin.stat:
        path: "{{ install_jenkins_agent__log_path }}"

    - name: "Create home path"
      when: not folder_check.stat.exists
      ansible.builtin.file:
        path: "{{ install_jenkins_agent__log_path }}"
        state: directory
        recurse: yes
        mode: "0700"
        group: "{{ install_jenkins_agent__group }}"
        owner: "{{ install_jenkins_agent__user }}"

- name: "Import Jenkins Agent service file"
  notify: "Enable and start Jenkins Agent"
  ansible.builtin.template:
    src: "templates/jenkins-agent.service.j2"
    dest: "/etc/systemd/system/jenkins-agent.service"
    mode: "0600"
    group: "root"
    owner: "root"
    lstrip_blocks: yes

- name: "Import Jenkins Agent starter script"
  notify: "Enable and start Jenkins Agent"
  ansible.builtin.template:
    src: "templates/jenkins-start-agent.sh.j2"
    dest: "{{ install_jenkins_agent__home }}/jenkins-start-agent.sh"
    mode: "0700"
    group: "{{ install_jenkins_agent__group }}"
    owner: "{{ install_jenkins_agent__user }}"
    lstrip_blocks: yes
