---
- name: "Converge"
  hosts: "cicd-debian-12"
  tasks:

    - name: "Include labocbz.install_jenkins_agent__"
      tags:
        - "labocbz.install_jenkins_agent"
      vars:
        install_jenkins_agent___user: "{{ inv_install_jenkins_agent___user }}"
        install_jenkins_agent___group: "{{ inv_install_jenkins_agent___group }}"
        install_jenkins_agent___password: "{{ inv_install_jenkins_agent___password }}"
        install_jenkins_agent___docker_based: "{{ inv_install_jenkins_agent___docker_based }}"
        install_jenkins_agent___name: "{{ inv_install_jenkins_agent___name }}"
        install_jenkins_agent___home: "{{ inv_install_jenkins_agent___home }}"
        install_jenkins_agent___master_remote: "{{ inv_install_jenkins_agent___master_remote }}"
        install_jenkins_agent___jar: "{{ inv_install_jenkins_agent___jar }}"
        install_jenkins_agent___secret: "{{ inv_install_jenkins_agent___secret }}"
        install_jenkins_agent___log_path: "{{ inv_install_jenkins_agent___log_path }}"
        install_jenkins_agent___ca: "{{ inv_install_jenkins_agent___ca }}"
        install_jenkins_agent___https_check: "{{ inv_install_jenkins_agent___https_check }}"
        install_jenkins_agent___basic_auth_login: "{{ inv_install_jenkins_agent___basic_auth_login }}"
        install_jenkins_agent___basic_auth_password: "{{ inv_install_jenkins_agent___basic_auth_password }}"
        install_jenkins_agent___basic_auth: "{{ inv_install_jenkins_agent___basic_auth }}"
      ansible.builtin.include_role:
        name: "labocbz.install_jenkins_agent"
