---
- name: "Converge"
  hosts: "cicd-debian-12"
  tasks:

    - name: "Include labocbz.install_jenkins__agent"
      tags:
        - "labocbz.install_jenkins_agent"
      vars:
        install_jenkins__agent_user: "{{ inv_install_jenkins__agent_user }}"
        install_jenkins__agent_group: "{{ inv_install_jenkins__agent_group }}"
        install_jenkins__agent_password: "{{ inv_install_jenkins__agent_password }}"
        install_jenkins__agent_docker_based: "{{ inv_install_jenkins__agent_docker_based }}"
        install_jenkins__agent_name: "{{ inv_install_jenkins__agent_name }}"
        install_jenkins__agent_home: "{{ inv_install_jenkins__agent_home }}"
        install_jenkins__agent_master_remote: "{{ inv_install_jenkins__agent_master_remote }}"
        install_jenkins__agent_jar: "{{ inv_install_jenkins__agent_jar }}"
        install_jenkins__agent_secret: "{{ inv_install_jenkins__agent_secret }}"
        install_jenkins__agent_log_path: "{{ inv_install_jenkins__agent_log_path }}"
        install_jenkins__agent_ca: "{{ inv_install_jenkins__agent_ca }}"
        install_jenkins__agent_https_check: "{{ inv_install_jenkins__agent_https_check }}"
        install_jenkins__agent_basic_auth_login: "{{ inv_install_jenkins__agent_basic_auth_login }}"
        install_jenkins__agent_basic_auth_password: "{{ inv_install_jenkins__agent_basic_auth_password }}"
        install_jenkins__agent_basic_auth: "{{ inv_install_jenkins__agent_basic_auth }}"
      ansible.builtin.include_role:
        name: "labocbz.install_jenkins_agent"
