---
- name: "Enable and start Jenkins Agent"
  register: install_jenkins_agent_service_status
  changed_when: install_jenkins_agent_service_status.state != "restarted"
  ansible.builtin.service:
    name: "jenkins_agent"
    state: "started"
    enabled: yes

- name: "Restart Jenkins Agent"
  register: install_jenkins_agent_service_status
  changed_when: install_jenkins_agent_service_status.state != "restarted"
  ansible.builtin.service:
    name: "jenkins_agent"
    state: "restarted"
    daemon_reload: true
