---
- name: "Converge"
  hosts: "all"
  tasks:
    # replace these tasks with whatever you find suitable to test
    - name: "Copy something to test use of synchronize module"
      ansible.builtin.copy:
        src: "/etc/hosts"
        dest: "/tmp/hosts-from-controller"
        mode: 0700

    - name: "Include labocbz.install_jenkins_agent"
      tags:
        - "labocbz.install_jenkins_agent"
      vars:
        install_jenkins_agent_user: "{{ inv_install_jenkins_agent_user }}"
        install_jenkins_agent_group: "{{ inv_install_jenkins_agent_group }}"
        install_jenkins_agent_password: "{{ inv_install_jenkins_agent_password }}"
        install_jenkins_agent_docker_based: "{{ inv_install_jenkins_agent_docker_based }}"
        install_jenkins_agent_name: "{{ inv_install_jenkins_agent_name }}"
        install_jenkins_agent_home: "{{ inv_install_jenkins_agent_home }}"
        install_jenkins_agent_master_remote: "{{ inv_install_jenkins_agent_master_remote }}"
        install_jenkins_agent_jar: "{{ inv_install_jenkins_agent_jar }}"
        install_jenkins_agent_secret: "{{ inv_install_jenkins_agent_secret }}"
        install_jenkins_agent_log_path: "{{ inv_install_jenkins_agent_log_path }}"
        install_jenkins_agent_ca: "{{ inv_install_jenkins_agent_ca }}"
        install_jenkins_agent_https_check: "{{ inv_install_jenkins_agent_https_check }}"
        install_jenkins_agent_basic_auth_login: "{{ inv_install_jenkins_agent_basic_auth_login }}"
        install_jenkins_agent_basic_auth_password: "{{ inv_install_jenkins_agent_basic_auth_password }}"
        install_jenkins_agent_basic_auth: "{{ inv_install_jenkins_agent_basic_auth }}"
      ansible.builtin.include_role:
        name: "labocbz.install_jenkins_agent"
