---
- name: "Converge"
  hosts: "cicd-ubuntu-22"
  tasks:

    - name: "Include labocbz.install_jenkins_agent__"
      tags:
        - "labocbz.install_jenkins_agent"
      vars:
        install_jenkins_agent__user: "{{ inv_install_jenkins_agent__user }}"
        install_jenkins_agent__group: "{{ inv_install_jenkins_agent__group }}"
        install_jenkins_agent__password: "{{ inv_install_jenkins_agent__password }}"
        install_jenkins_agent__docker_based: "{{ inv_install_jenkins_agent__docker_based }}"
        install_jenkins_agent__name: "{{ inv_install_jenkins_agent__name }}"
        install_jenkins_agent__home: "{{ inv_install_jenkins_agent__home }}"
        install_jenkins_agent__master_remote: "{{ inv_install_jenkins_agent__master_remote }}"
        install_jenkins_agent__jar: "{{ inv_install_jenkins_agent__jar }}"
        install_jenkins_agent__secret: "{{ inv_install_jenkins_agent__secret }}"
        install_jenkins_agent__log_path: "{{ inv_install_jenkins_agent__log_path }}"
        install_jenkins_agent__ca: "{{ inv_install_jenkins_agent__ca }}"
        install_jenkins_agent__https_check: "{{ inv_install_jenkins_agent__https_check }}"
        install_jenkins_agent__basic_auth_login: "{{ inv_install_jenkins_agent__basic_auth_login }}"
        install_jenkins_agent__basic_auth_password: "{{ inv_install_jenkins_agent__basic_auth_password }}"
        install_jenkins_agent__basic_auth: "{{ inv_install_jenkins_agent__basic_auth }}"
      ansible.builtin.include_role:
        name: "labocbz.install_jenkins_agent"
